project 'YunBaseApp.xcodeproj'

# Uncomment the next line to define a global platform for your project
platform :ios, '8.0'
inhibit_all_warnings!

target 'YunBaseApp' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for YunBaseApp
  pod 'AFNetworking', '~> 3.0'
  pod 'Masonry'
  pod 'Mantle'
  pod 'YunKits'

end
